import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os
from pathlib import Path

BASE_DIR = Path(__file__).parent
EDA_DIR = BASE_DIR / "eda_outputs"
os.makedirs(EDA_DIR, exist_ok=True)

def perform_eda(filepath, report_lines):
    df = pd.read_csv(filepath)
    filename = Path(filepath).name
    
    if filename == "insurance.csv":
        ins_type = "Claim"
        target_col = "claim"
    else:
        ins_type = filename.split('_insurance')[0].capitalize()
        if 'Premium_Amount' in df.columns:
            target_col = 'Premium_Amount'
        elif 'Premium' in df.columns and 'Annual_Premium' not in df.columns:
            target_col = 'Premium'
        elif 'Annual_Premium' in df.columns:
            target_col = 'Annual_Premium'
        else:
            return
            
    if target_col not in df.columns:
         return

    print(f"Generating EDA for {ins_type} ({filename})...")
    type_dir = EDA_DIR / ins_type
    os.makedirs(type_dir, exist_ok=True)
    
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()

    # Dist Plot for Target
    plt.figure(figsize=(8, 5))
    sns.histplot(df[target_col].dropna(), kde=True, color='blue', bins=50)
    plt.title(f"Distribution of {target_col} - {ins_type}")
    plt.tight_layout()
    plt.savefig(type_dir / f"{ins_type}_target_distribution.png")
    plt.close()
    
    # Correlation Heapmap
    if len(num_cols) > 1:
        plt.figure(figsize=(10, 8))
        corr = df[num_cols].corr()
        sns.heatmap(corr, annot=True, cmap="vlag", fmt=".2f")
        plt.title(f"Correlation Map - {ins_type}")
        plt.tight_layout()
        plt.savefig(type_dir / f"{ins_type}_correlation_matrix.png")
        plt.close()
        
    # NCB Impact Plot
    if 'No_Claim_Years' in df.columns:
        plt.figure(figsize=(8, 5))
        sns.boxplot(data=df, x='No_Claim_Years', y=target_col, palette="Set2")
        plt.title(f"Impact of No Claim Years on {target_col} - {ins_type}")
        plt.tight_layout()
        plt.savefig(type_dir / f"{ins_type}_ncb_impact.png")
        plt.close()

    # Scatter of top 2 correlated nums against target
    if len(num_cols) > 1:
        top_corrs = corr[target_col].drop(target_col).abs().sort_values(ascending=False).head(2).index.tolist()
        for col in top_corrs:
            plt.figure(figsize=(7, 5))
            sns.scatterplot(data=df, x=col, y=target_col, alpha=0.3, color='darkorange')
            plt.title(f"{target_col} vs {col} - {ins_type}")
            plt.tight_layout()
            plt.savefig(type_dir / f"{ins_type}_scatter_vs_{col}.png")
            plt.close()
            
    # Boxplots for Categorical
    for cat in cat_cols[:4]: # Limit to max 4 to save time
        if df[cat].nunique() < 10:
            plt.figure(figsize=(8, 5))
            sns.boxplot(data=df, x=cat, y=target_col, palette="pastel")
            plt.title(f"{target_col} grouped by {cat} - {ins_type}")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.savefig(type_dir / f"{ins_type}_box_{cat}.png")
            plt.close()

    # Add to Summary Report
    report_lines.append(f"### {ins_type} Insurance EDA Summary")
    report_lines.append(f"- **Total Records:** {len(df):,}")
    report_lines.append(f"- **Target Variable:** `{target_col}` (Mean: {df[target_col].mean():.2f})")
    
    if len(num_cols) > 1:
        # Note the highest positive and negative correlations
        target_corr = corr[target_col].drop(target_col)
        highest_pos = target_corr.idxmax()
        highest_neg = target_corr.idxmin()
        report_lines.append(f"- **Strongest Positive Correlation:** `{highest_pos}` ({target_corr[highest_pos]:.2f})")
        report_lines.append(f"- **Strongest Negative Correlation:** `{highest_neg}` ({target_corr[highest_neg]:.2f}) (Note: `No_Claim_Years` usually has a strong negative correlation due to the compounded 2% discount strategy)")
    report_lines.append("")

if __name__ == "__main__":
    csv_files = glob.glob(str(BASE_DIR / '*_insurance_*.csv'))
    csv_files.append(str(BASE_DIR / 'insurance.csv'))
    summary_lines = ["", "## 📈 Comprehensive Exploratory Data Analysis (EDA)", "", "This section was automatically generated by iterating across all insurance datasets to find key analytical relationships. Visual plots mapping detailed correlations, Box-Whisker category spreads, and Target Distributions have been rendered locally in the `eda_outputs` repository directory."]
    
    for f in csv_files:
        try:
            perform_eda(f, summary_lines)
        except Exception as e:
            print(f"Error skipping EDA for {f}: {e}")
            
    with open(BASE_DIR / "Project_Report.md", "a", encoding='utf-8') as f:
        f.write("\n".join(summary_lines) + "\n")
        
    print("EDA Generation Complete! Graphs stored in eda_outputs and Project_Report.md appended.")
